export const symbolActions = {
    GET_SYMBOL_LIST_SUCCESS: 'GET_SYMBOL_LIST_SUCCESS',
    SET_SYMBOL_LIST_ERROR: 'SET_SYMBOL_LIST_ERROR'
};

export const quotesActions = {
    GET_QUOTE_INFO_SUCCESS: 'GET_QUOTE_INFO_SUCCESS',
    SET_QUOTE_INFO_ERROR: 'SET_QUOTE_INFO_ERROR'
};

